import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/app/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, components, pageProps }) {
  return (
    <CartProvider {...metadata}>
      <html lang="en">
        <body {...pageProps} className={inter.className}>
          {children}
        </body>
      </html>
    </CartProvider>
  );
}
