





export const products = [
  {
    id: 1,
    Image: "/casio.svg",
    type: "Casio",
    model: "CA-500WE-1AEF",
    description: "Perennial favourite since its 1980s debut...",
    price: "N160,002",
    rating: "/rating.svg",
    Number: 8,
    stock: "17",
  },
  {
    id: 2,
    Image: "/rolex2.svg",
    type: "Rolex",
    model: "GMT-MASTER II 126713GRNR",
    description:
      "Unidirectional rotatable bezel and solid-link Oyster bracelet...",
    price: "N301,899",
    rating: "/rating.svg",
    Number: 5,
    stock: "6",
  },
  {
    id: 3,
    Image: "/rolex.svg",
    type: "Rolex",
    model: "36mm Stainless Steel",
    description: "Q Timex Malibu Stainless Steel Expansion Band Watch",
    price: "N175,054",
    rating: "/rating.svg",
    Number: 18,
    stock: "6",
  },
  {
    id: 4,
    Image: "/mondaine.svg",
    type: "Mondaine",
    model: "Classic 40mm Vegan Watch",
    description:
      "Robust design inspired by the renowned Swiss Railway clock...",
    price: "N194,542",
    rating: "/rating.svg",
    Number: 42,
    stock: "6",
  },
  {
    id: 5,
    Image: "/ligure.svg",
    type: "Ligure",
    model: "LWT23001N",
    description:
      "Steel silver with a diameter of 41 mm crafted perfectly for you...",
    price: "N160,002",
    rating: "/rating.svg",
    Number: 8,
    stock: "17",
  },
  {
    id: 6,
    Image: "/certina.svg",
    type: "Certina",
    model: "DS Action C0329291104100",
    description:
      "Inside the case lies a ETA movement and a Sapphire crystal...",
    price: "N301,889",
    rating: "/rating.svg",
    Number: 24,
    stock: "6",
  },
  {
    id: 7,
    Image: "/timex.svg",
    type: "Timex",
    model: "TW2W21200 Celestial Automatic",
    description: "Stainless steel open heart automatic watch",
    price: "N175,054",
    rating: "/rating.svg",
    Number: 14,
    stock: "6",
  },
  {
    id: 8,
    Image: "/seiko.svg",
    type: "Seiko",
    model: "SWR054P1 Selection Nano Watch",
    description: "Rectangular Ladies Quartz Watch with 2 Year Warranty.",
    price: "N194,542",
    rating: "/rating.svg",
    Number: 10,
    stock: "6",
  },
  {
    id: 9,
    Image: "/balmain.svg",
    type: "Balmain",
    model: "B3912.39.82",
    description: "Classic ladies watch with mother of pearl dial...",
    price: "N160,002",
    rating: "/rating.svg",
    Number: 9,
    stock: "17",
  },
  {
    id: 10,
    Image: "/casio2.svg",
    type: "Casio",
    model: "MTP-1302PD-3AVEF",
    description: "Analog quartz watch with date made of metal alloy...",
    price: "N301,899",
    rating: "/rating.svg",
    Number: 19,
    stock: "6",
  },
  {
    id: 11,
    Image: "/casio3.svg",
    type: "Casio",
    model: "MW-240-1EVEF",
    description: "A diameter of 43.6 mm and is fitted with a Resin strap...",
    price: "N175,054",
    rating: "/rating.svg",
    Number: 36,
    stock: "6",
  },
  {
    id: 12,
    Image: "/garonne.svg",
    type: "Garonne",
    model: "KQ29Q475",
    description: "Rugged analog and digital sports watch for boys...",
    price: "N194,542",
    rating: "/rating.svg",
    Number: 102,
    stock: "6",
  },
  {
    id: 13,
    Image: "/balmain2.svg",
    type: "Balmain",
    model: "LA-20WH-2AEF",
    description: "Splash waterproof blue retro digital watch...",
    price: "N160,002",
    rating: "/rating.svg",
    Number: 41,
    stock: "17",
  },
  {
    id: 14,
    Image: "/lorus.svg",
    type: "Lorus",
    model: "Sport RRX09HX9",
    description: "Ladies sports watch. Case made of Steel silver...",
    price: "N301,899",
    rating: "/rating.svg",
    Number: 45,
    stock: "6",
  },
  {
    id: 15,
    Image: "/icewatch.svg",
    type: "Ice-Watch",
    model: "022801 ICE",
    description: "Smartwatch for kids with case made of Resin of 36 mm...",
    price: "N11,700",
    rating: "/rating.svg",
    Number: 32,
    stock: "6",
  },
  {
    id: 16,
    Image: "/calypso.svg",
    type: "Calypso",
    model: "Junior 10-15 K5801/4",
    description: "Digital kids watch Resin with a diameter of 35 mm",
    price: "N194,542",
    rating: "/rating.svg",
    Number: 87,
    stock: "6",
  },
];
